### ISSUE TITLE
the handle/name of tweet author should be clickable

### ISSUE THREAD

**Issue by rajatjindal** [rajatjindal/translatethread-ui#5]
e.g. look at https://translatethread.com/thread/1411506884201238529, the author handle `brolo_rodrigo` should be clickable and link to the author's twitter profile.

**Comment by hufuhufu** [comment]
Hello, I made a PR that should make the author handle clickable. And I also made it to have underline on hover, just like Twitter's behavior.

**Comment by rajatjindal** [comment]
thank you for the PR. i have merged it
